name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Add Capacitor Android
        run: |
          npx cap add android --skip-deps || true
          npx cap sync android

      - name: Build web app
        run: |
          mkdir -p www
          cp index.html www/

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: vigas-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
