naname: Build Android App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g @ionic/cli @capacitor/cli
          npm install
          npm install @capacitor/android

      - name: Build web app
        run: |
          npm run build || echo "No build script, using /www directly"

      - name: Add Android platform
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          else
            echo "Android platform already exists"
          fi

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build APK and AAB
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug
          ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Vigas-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: Vigas-AAB
          path: android/app/build/outputs/bundle/release/app-release.aab
