name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Prepare web directory
        run: |
          mkdir -p www
          cp index.html www/index.html

      - name: Initialize Capacitor Android project
        run: |
          npx cap init vigas com.rjpedro.vigas --web-dir=www
          npx cap add android

      - name: Build web app
        run: npm run build || echo "No build step, using index.html"

      - name: Copy web assets to Android
        run: npx cap copy android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
